### ISSUE TITLE
guess the number game in python 

### ISSUE THREAD

**Issue by bitbroke** [d-coder111/SpectrumOfPython#6]
In this game, the player tries to guess a random number between 1 and 100 in the least number of attempts. After each guess, the game will tell the player if their guess was too high or too low. The game continues until the player guesses the correct number.

**Comment by bitbroke** [comment]
please assign this project to me under hactoberfest2024

**Comment by d-coder111** [comment]
Hey @bitbroke , someone has already added the same game..pls try adding different python related project maybe a game or data science project or anything built using python, I will definitely merge that. Also It's hacktoberfest accepted repo so your contributions will be considered.
